# This is an attempt to generate the walkability map by hosting an extract of OSM as a WMS server using
# Geoserver and PostGIS
# 
# https://wiki.openstreetmap.org/wiki/WMS

services:
  geoserver:
    build: geoserver/
    ports:
      - "8080:8080"

    environment:
      - GEOSERVER_ADMIN_PASSWORD_FILE=/run/secrets/GEOSERVER_ADMIN_PASSWORD
      - STABLE_EXTENSIONS=css-plugin

    secrets:
      - GEOSERVER_ADMIN_PASSWORD
      - POSTGRES_PASS

  postgis:
    build: postgis/
    expose:
      - "5432"
    
    environment:
      - POSTGRES_PASS_FILE=/run/secrets/POSTGRES_PASS
    
    secrets:
      - POSTGRES_PASS

secrets:
  GEOSERVER_ADMIN_PASSWORD:
    file: secrets/geoserver_admin_password.txt
  POSTGRES_PASS:
    file: secrets/postgres_user_password.txt